# Generated by Django 4.2.1 on 2023-05-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=36, unique=True)),
                (
                    "ip",
                    models.GenericIPAddressField(default="0.0.0.0", protocol="IPv4"),
                ),
                ("private_key", models.BinaryField()),
                ("public_key", models.BinaryField()),
                ("share_key", models.BinaryField(default=None, null=True)),
            ],
        ),
    ]
